### PR TITLE
[Blocked v2] Fixed typo "cart" to "card"

### PR DESCRIPTION
**Pull request by peshi**

### CODE REVIEW

**Comment by mmoreram** [comment]
This commit is not that easy to be merged indeed. This change introduces a lot of method name changes that would break a lot of things.

Let's keep opened this PR and during next days we'll decide what to do with this repository :)

Thanks :)

**Comment by peshi** [comment]
Np, btw. What is the purpose of cart_route / cart_thanks, since I renamed with replace with I don't know if it refers to a shopping cart route. Let me know, that is the case I'll revert the routes.

**Comment by peshi** [comment]
Ah, nevermind, checked it was a typo :)

**Comment by mmoreram** [comment]
@peshi I really appreciate efforts to improve a library. Is something I've really missed in this package so far. So, I will completely use this PR when reaching next v2 of PaymentSuite, based in a bigger community and a group of collaborators and deciders.

Thanks again :)

**Pull request closed without merging**
